_base_ = './cascade_rcnn_r50_fpn_2x.py'
model = dict(
    type='CascadeRCNN',
    # pretrained='modelzoo://resnet50',
    backbone=dict(
        type='ResNetCBam',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(
            type='BN', #设置bn层
            requires_grad=True),
        norm_eval=True,
        style='pytorch'),)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[32, 38])
total_epochs = 40
checkpoint_config = dict(interval=5)
work_dir = '../data/work_dirs/cascade_rcnn_r50_detectors_2x_cbam'
# load_from = None
load_from = '../data/pretrained/cascade_rcnn_r50_fpn_20e_coco_bbox_mAP-0.41_20200504_175131-e9872a90.pth' #加载预训练网络参数