_base_ = '../frequency_config/cascade_rcnn_r50_detectors_40e_l1440.py'
model = dict(
    type='CascadeRCNN',
    # pretrained='modelzoo://resnet50',
    backbone=dict(
        type='FreqNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(
            type='BN', #设置bn层
            requires_grad=True),
        norm_eval=True,
        style='pytorch'),)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[16, 22])
total_epochs = 24
checkpoint_config = dict(interval=5)
load_from = None
work_dir = '../data/work_dirs/cascade_rcnn_r50_detectors_2x_freqnet_l1440'